apiVersion: v1
kind: Secret
metadata:
  name: n8n-owner-credentials
  namespace: n8n
type: Opaque
stringData:
  email: "admin@example.com"
  password: "ChangeMe123!"
  first_name: "Admin"
  last_name: "User"
