apiVersion: v1
kind: Service
metadata:
  name: n8n-service-simple
  namespace: n8n
  labels:
    app: n8n-simple
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "${LB_TYPE:-nlb}"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "${LB_SCHEME:-internet-facing}"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "${LB_CROSS_ZONE:-true}"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "${LB_TARGET_TYPE:-ip}"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "5678"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/healthz"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5678
    protocol: TCP
    name: http
  selector:
    app: n8n-simple
